import type { ReactNode } from 'react';
import Nav from './components/Nav'; // Adjust the path as needed
import "./styles/globals.css";

// Assuming "Inter" font and "metadata" are used elsewhere or in a custom _document.tsx or _app.tsx
// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <div>
      <Nav /> {/* Include the Nav component at the top */}
      <main>{children}</main> {/* Main content area for child components/pages */}
    </div>
  );
}
